name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  card_swiper: ^3.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.4.9
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.0.1
  intl: ^0.19.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.1.2
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.8
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app-icon-2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app-icon-2.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app-icon-2.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app-icon-2.png"

flutter_native_splash:
  color : "#252829"
  android_12:
    color: "#252829"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/icons/
